### PR TITLE
Refactored the CSS in the donation goal styles with BEM

### PR DESCRIPTION
**Pull request by ivy-g**
updated the donation styles to use BEM
[https://github.com/code-corps/code-corps-ember/issues/673]

### CODE REVIEW

**Comment by ivy-g** [comment]
@rileytaylor I've made the changes, could you have another look?

**Comment by rileytaylor** [comment]
Still missing a few of the templates that'll need changes (mostly in the `templates/components/donations` folder), otherwise great work so far

**Comment by JoshSmith** [comment]
@ivy-g looks like there were some test failures created here. Let me know if you want someone to help you identify what and how to fix it.

**Comment by ivy-g** [comment]
@JoshSmith @rileytaylor is working them out with me

**Comment by rileytaylor** [comment]
@ivy-g @JoshSmith I'm going to continue working through this and figure out these failing tests

**Comment by rileytaylor** [comment]
Status Update- Down to 6 failing tests from 25, will probably need to rewrite some of these tests to page objects to fix a few of these.

**Comment by rlueder** [comment]
Is this still pending? Is it ok if I take a stab at it?

**Comment by JoshSmith** [comment]
@rlueder @rileytaylor was helping @ivy-g but you can see there's a ton of conflicts now that need resolved.

**Comment by rlueder** [comment]
Yeah, I was volunteering to resolve the conflicts. 😄

**Comment by rileytaylor** [comment]
@rlueder Yeah still pending, haven't had much time to work on this. What would actually be very helpful is if you could convert some of these tests into page objects: https://github.com/code-corps/code-corps-ember/issues/715 exists for donation-goal-edit but [donation-goal-test.js](https://github.com/code-corps/code-corps-ember/blob/develop/tests/integration/components/donation-goal-test.js) and [donation-goals-test.js](https://github.com/code-corps/code-corps-ember/blob/develop/tests/integration/components/donation-goals-test.js) also need to be converted to use page objects. If that is done I'll be able to resolve most of those conflicts!

**Comment by rileytaylor** [comment]
I'm closing this pr and circling back due to a large number of changes that will create a merge nightmare. Particularly since several of these components will be moving to `components/donation/goals`. @ivy-g we should do these again on a fresh branch once the files are in all the right places. We also have a much better workflow for resolving these tests and decoupling them. This pull was incredibly helpful in identifying what needed to be done. @JoshSmith @rlueder

**Pull request closed without merging**
