### PR TITLE
Styles for card-item from tickets #675 and #676

### LINKED ISSUE #675: Implement CSS styling for card-list component
# Problem

The `card-list` component, although implemented, lacks any kind of styling.

## Subtasks
- [x] Add styles to the component, using BEM (as described in #672)

### LINKED ISSUE #676: Add "add card" button to the card-list component
# Problem

The `card-list` component needs an add card button to show the `credit-card` component.

## Subtasks
- [ ] Add the add card button
- [ ] Write tests for it

### PR DESCRIPTION
**Pull request by rlueder**
# What's in this PR?

- updated name of class added to cards on the list from "selected" to "card-item--selected" so it follows BEM conventions;
- created new stylesheet: components/donation/card-item.scss;
- adjusted font-weight of h3 elements to match Sketch design (semi-bold instead of bold);
- added font-size to html element (14px $body-font-size-normal) so that em units can use it as a reference;
- added title and button to donation-container.hbs (see reference to #676 below)

card-item

## References

Fixes #675 
- radio buttons still need styling to match Sketch mockups

Closes #676 
- "Add Card" is static at the moment;
- style for this button has to be moved to _buttons.scss (and all buttons should be updated to BEM naming convention)

### CODE REVIEW

**Comment by JoshSmith** [comment]
Mentioned in conversation but these radio buttons look fine. Do not need to style to match mockups exactly.

**Comment by JoshSmith** [comment]
@rlueder there are some upstream changes you'll have to fetch from this repo and deconflict. Let me know if you need help on it. Can compare.

**Comment by rlueder** [comment]
TO DO
- get the brand asset to match the card added by referencing the last 4 digits (e.g. 4242 loads the Visa asset, 4444 loads Mastercard, etc.);
- update the radio buttons to checked if the user clicks anywhere inside the card item (would an addon like [ember-radio-button](https://github.com/yapplabs/ember-radio-button) be overkill?);
- [write a helper](https://guides.emberjs.com/v2.2.0/templates/writing-helpers/) to pass future month and year to expiration date so tests won't break in the future  (@JoshSmith's clever suggestion);

**Comment by JoshSmith** [comment]
@rlueder instead of hitting merge can you rebase?

**Comment by JoshSmith** [comment]
Awesome work @rlueder 🙌

**Pull request merged**
