### PR TITLE
Rename posts to tasks

### LINKED ISSUE #454: Rename posts to tasks
# Problem

In advance of our redesign, we want to rename Posts and all reference to them as Tasks.

## References

Related to https://github.com/code-corps/code-corps-api/issues/244

### PR DESCRIPTION
**Pull request by dennybiasiolli**
Fixes #454

### CODE REVIEW

**Comment by JoshSmith** [comment]
Wow, thank you @dennybiasiolli!

I'm going to mark as blocked because we want to do the same in the API, and then this will be good to merge pending a review from one of us.

**Comment by dennybiasiolli** [comment]
@JoshSmith I'll write the first commit as separate PR because without that commit tests are broken also in develop branch. Don't you noticed that?

**Comment by JoshSmith** [comment]
@dennybiasiolli I haven't seen that because it works on CI and locally. But that sounds good as a separate PR! If it's breaking for you locally, then that's definitely a problem.

**Comment by JoshSmith** [comment]
@dennybiasiolli I've prioritized making this change in the API. Not sure when I'll get to it specifically but hoping very soon. You can see its status here: https://github.com/code-corps/code-corps-api/projects/4

**Comment by dennybiasiolli** [comment]
ok @JoshSmith , thanks! I can try to take a look tomorrow morning (here is GMT+2) if I can help with something

**Comment by JoshSmith** [comment]
@dennybiasiolli okay, great. I'll try to see if I can get the post renaming task done over there.

**Comment by JoshSmith** [comment]
@dennybiasiolli once those fixes are made, let me know. Don't squash that change just yet, either. I'd prefer to see the separate commit, if you don't mind.

My API PR is likely to be merged soon. Looks all good.

**Comment by dennybiasiolli** [comment]
@JoshSmith done. Let me know when I have to squash the two commits.

**Comment by JoshSmith** [comment]
🎈 🎈 

❤️ @dennybiasiolli! Thanks so much for this.

**Comment by JoshSmith** [comment]
It will be in production in just a few minutes!

**Comment by dennybiasiolli** [comment]
@JoshSmith I'm glad to help! :)

**Comment by JoshSmith** [comment]
@dennybiasiolli make sure you come 👋 hello in [our Slack](http://slack.codecorps.org/).

**Pull request merged**
