### PR TITLE
Enhancement/introduce ember suave

### PR DESCRIPTION
**Pull request by sarupbanskota**
# What's in this PR?

Introduces ember-suave for some stylish JavaScript 😎 
## References

Needs https://github.com/code-corps/code-corps-ember/pull/499 to be merged first.

Progress on: #499

### CODE REVIEW

**Comment by JoshSmith** [comment]
@sarupbanskota have you joined our Slack yet?

**Comment by sarupbanskota** [comment]
@JoshSmith I did try to request an invite but the form doesn't seem to submit. Would you mind inviting me? Email on my GH profile :-)

**Comment by sarupbanskota** [comment]
`ember-suave` done! Pretty sure the CI will go green.

I've had to switch off the following list of rules for now, to get CI to green.

- [ ] comma-dangle
- [ ] spaced-comment
- [ ] object-shorthand
- [ ] quotes
- [ ] brace-style
- [ ] max-statements-per-line
- [ ] keyword-spacing
- [ ] no-var
- [ ] space-in-parens
- [ ] generator-star-spacing
- [ ] indent
- [ ] space-infix-ops
- [ ] operator-linebreak
- [ ] object-curly-spacing
- [ ] dot-notation
- [ ] no-console
- [ ] prefer-template
- [ ] space-before-function-paren
- [ ] comma-spacing
- [ ] no-multiple-empty-lines
- [ ] camelcase
- [ ] no-trailing-spaces
- [ ] key-spacing
- [ ] new-cap
- [ ] one-var
- [ ] space-before-blocks
- [ ] ember-suave/no-const-outside-module-scope
- [ ] ember-suave/no-direct-property-access
- [ ] ember-suave/prefer-destructuring
- [ ] ember-suave/require-access-in-comments
- [ ] ember-suave/require-const-for-ember-properties

------------

Some of them are surely going to be pretty hairy to solve. With them switched off, as this still reflects the styling of the project, I suggest we merge this in, and we can start one PR each per rule (or per few simple rules), and remove the rule off the `eslint` file. I know that sounds like a lot of PRs, but otherwise I think it's going to be difficult to review, not to mention too many changes in too few commits. What do you folks think? I'm happy to start on some of them.

**Comment by sarupbanskota** [comment]
Yay, as expected, it's green :-)

@JoshSmith can you confirm if this looks good, and if you agree with the plan, and I'll rebase/squash on top of my other branch?

**Comment by JoshSmith** [comment]
@sarupbanskota I agree with your assessment here.

**Comment by JoshSmith** [comment]
Rebase and squash and we'll be good to go!

**Comment by sarupbanskota** [comment]
Done. Rebased, squashed, greenified :-)

You can merge this now @JoshSmith

**Comment by JoshSmith** [comment]
@sarupbanskota can you open an issue for fixing `ember-suave` now?

**Comment by JoshSmith** [comment]
🙌

**Pull request merged**
