### PR TITLE
[WIP] payments/funds-recipient/personal-id-number component

### PR DESCRIPTION
**Pull request by pixelhandler**
# What's in this PR?

- WIP for new `payments/funds-recipient/personal-id-number` component 

## References

Progress on: #886

### CODE REVIEW

**Comment by pixelhandler** [comment]
This is only work in progress, will squash later when closer to complete

**Comment by begedin** [comment]
I hope it's ok for me to take this over and try and wrap it up today. Good work up to this point.

**Comment by pixelhandler** [comment]
There is more work still to be done, I think the logic isn't right for showing the verifying message, prolly needs to be there with a disabled submit button. I'm TDD'ing so that will be the next step.

**Comment by begedin** [comment]
@pixelhandler This is the last bit of the puzzle, really, feature-wise, so I'll take over and wrap up today. Good work so far.

**Comment by pixelhandler** [comment]
@begedin ok thanks!

**Comment by JoshSmith** [comment]
Think this was superseded by #906.

**Pull request closed without merging**
