### PR TITLE
Fix ESLint offences Round 2

### PR DESCRIPTION
**Pull request by sarupbanskota**
# This is a WIP PR
- key-spacing

Make sure any changes to code include changes to documentation.
## References

Fixes #

Progress on: #

http://eslint.org/docs/rules/key-spacing
enforce consistent spacing between keys and values in object literal properties

This rule enforces spacing around the colon in object literal properties.
It can verify each property individually, or it can ensure horizontal
alignment of adjacent properties in an object literal.

### CODE REVIEW

**Comment by JoshSmith** [comment]
@sarupbanskota there are some merge conflicts here. Can you rebase?

**Comment by JoshSmith** [comment]
Hey @sarupbanskota, just checking in!

**Comment by sarupbanskota** [comment]
sorry again! I'll be back on it this weekend! :)

**Comment by JoshSmith** [comment]
@sarupbanskota it looks like something went weird with your rebase.

**Comment by JoshSmith** [comment]
I have a bad feeling this PR might need to be closed. The history looks like it's really off now.

**Comment by sarupbanskota** [comment]
yep! :-( I'm sorry folks. I'll start another PR!

**Comment by sarupbanskota** [comment]
sorry folks, back with the cliche excuse - got really busy with $DAYJOB, sigh!

Closing this and made progress on https://github.com/code-corps/code-corps-ember/pull/653

I've enforced horizontal alignment for JSON - y'all should like it :)

**Comment by JoshSmith** [comment]
@sarupbanskota no need to apologize! I totally understand. I just feel bad when things get outdated for you.

**Pull request closed without merging**
