### PR TITLE
Added filtering by post status

### LINKED ISSUE #214: Add ability to filter to open/closed issues

### PR DESCRIPTION
**Pull request by begedin**
Closes #214 

I generalized the `post-filter-dropdown` component a bit, so we can use it both for type and status filters. The filter behavior itself, though, which is defined at controller level is semi-exclusive, meaning that the filter can be either open or closed (or neither). It cannot be both open and closed at the same time. Considering that, there is no "all" button to remove status filters from the page. Instead, we simply select another filter, or click to dismiss the current filter.

### CODE REVIEW

**Comment by begedin** [comment]
Requires code-corps/code-corps-api#321

**Comment by JoshSmith** [comment]
A couple notes on this:

- Going to `/posts` is the default and the open status is the default. 👍 
- Clearing the filter changes the URL to `/posts?status=null`. This is maybe made moot if we implement following changes.
- Think that having a dropdown for this isn't as good as having just a couple links side-by-side that are `.active` or not.
- Don't think these should be added then to the list of filters displayed.

What do you think?

**Comment by begedin** [comment]
Links are something I considered, but the reason I went with dropdowns and dismissable filters once they are active was that we sill probably want to have the option to show all posts (both open and closed). In that case, we'd need either

* 3 exclusive buttons - "open", "closed", "both/all/any"
* 2 buttons that are toggleable, if just one status is enabled, show just that one status, if both are enabled, or both are disabled, show all posts and remove filter

I feel that the dropdown is more consistent with what we have, which is why I went with it. Having "status=null" in the URL is a bug, which I need to figure out.

**Comment by JoshSmith** [comment]
I'm not sure if I agree that we want to have an option to show both open and closed posts. What would be the use case for that? Have you ever wanted it on GitHub?

**Comment by begedin** [comment]
@JoshSmith I have used it before, simply to track down a specific issue for which I'm not sure if it's closed or not. It's a matter of removing the `is:open` part of the filter on github. Not sure how generally useful that is, though, but maybe we should look at how github does it either way.

They have a "closed" and "open" button as you said, as well as a textbox for custom filtering. We could go with the buttons now, and add the textbox in a future version.

**Comment by JoshSmith** [comment]
@begedin I've simplified a lot and will push up soon.

There are some things we need to change regardless.

**Comment by JoshSmith** [comment]
Here's a quick demo:

**Comment by hannah** [comment]
Looks good to me! 👍 🎉

**Comment by JoshSmith** [comment]
Yay. Thanks @hannah!

**Pull request merged**
