### PR TITLE
Attempt to add code coverage

### LINKED ISSUE #564: Add ember-cli-code-coverage
# Problem

Add some code coverage reporting. https://github.com/kategengler/ember-cli-code-coverage
## Subtasks
- [ ] Add the reporting
- [ ] Make the reporting work with Circle and Coveralls
- [ ] Add the Coveralls badge to the README

### PR DESCRIPTION
**Pull request by JoshSmith**
# What's in this PR?

Attempting to add code coverage. Doesn't work yet.
## References

Fixes #564

### CODE REVIEW

**Comment by JoshSmith** [comment]
No coverage being generated. Trying with `COVERAGE=true ember test`. Would appreciate someone else pulling down or spotting what I'm doing wrong.

**Comment by emosher** [comment]
I tried this too.  What error are you seeing?  For me it seems to chug along just fine until this happens:
```
ok 898 PhantomJS 1.9 - Unit | Utility | mention parser: it returns the unmodified task string when there are no mentions
not ok 899 PhantomJS 1.9 - Global error: INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable. at http://localhost:7357/5484/tests/index.html?hidepassed, line 1071
    ---
        Log: |
            { type: 'error',
              text: 'INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable. at http://localhost:7357/5484/tests/index.html?hidepassed, line 1071\n' }
    ...
not ok 900 PhantomJS 1.9 - Unit | Utility | mention parser: global failure
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/5484/tests/index.html?hidepassed:1071
        message: >
            INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
        Log: |
    ...

1..900
# tests 900
# pass  898
# skip  0
# fail  2
```

It then has another block saying "request aborted" and some additional error spewage.

**Comment by JoshSmith** [comment]
@emosher I don't actually see an error or even _any_ output at all. Nothing happens. No coverage generated whatsoever.

**Comment by JoshSmith** [comment]
We need to run with `COVERAGE=true`.

Also concerned that this is causing issues:

```
// in mirage/config.js

  this.passthrough('/write-coverage');
  this.namespace = 'api';  // It's important that the passthrough for coverage is before the namespace, otherwise it will be prefixed.
```

We don't use `namespace`, but wondering if perhaps we should be.

**Comment by JoshSmith** [comment]
@begedin thoughts on the above comment?

**Comment by begedin** [comment]
@JoshSmith I'm not sure how the namespace would interact with our actual app setup (where `api.` is just part of the URL). We should probably give it a try to see how it works.

**Comment by JoshSmith** [comment]
Actually it looks like `namespace` is not a subdomain but something like `/baz` in `foo.com/baz`.

**Pull request merged**
