### PR TITLE
Switch to project user system

### PR DESCRIPTION
**Pull request by begedin**
# What's in this PR?

List the changes you made and your reasons for them.

This PR does a major switch from `organizationMembers` to `projectUsers`. I tried doing it more granularly, but it ended up being too much of a pain.

The switch here is mostly complete. The couple of minor things that need doing are:

- [x] ~~Decide what to do with the remaining `joinProject` function in the `credentials` service. The one place it's used in could define it directly, or it could trigger a route action and we can define the action on the route.~~ Moved it into the component. It's not the best approach, but there's no point in having just that one function that's used in just that one spot in a separate service. Initially, I wanted to move it to a route action, but with the way our `project`, `project.index`, `project.settings` and `project.donate` templates are written, the component is used in several spots on several different routes, so we would have to write the action several times. I think we need to reconsider how our templates/routes are organized in these cases. Created issue #1122 to further deal with it.
- [x] ~~Decide what to do with the user profile page. Right now, it renders user's organizations through the `organizationMemberships` relation. I recommend instead adding a `hasMany('organizations')` to users as an inverse of `organization.owner` and rendering that. We can do this in a separate issue.~~  created #1121 to discuss
- [x] Also in a separate issue, possibly add a list of the user's project's on their profile page. Both those they own (as an inverse of `project.owner`) as well as those they contribute to (via `user.ProjectUsers`). - Actually added this by just renaming things. Seems to be working fine.
- [x] General code cleanup. There's some duplication marked with a TODO, and I'm sure there's unused code we need to remove
- [x] Decide what to do with the final remnants of `organizationMemberships` in the mirage scenarios, etc. - I just outright removed all that I could find.

### CODE REVIEW

**Comment by JoshSmith** [comment]
I think maybe we just kill organizations on a user's page and instead do something with projects.

**Comment by JoshSmith** [comment]
Wouldn't unused code be caught by coveralls @begedin?

**Comment by JoshSmith** [comment]
The project card appears to still be using organization members, as does I think the sidebar. Not sure where else. Is this an oversight, or intended to be done as a separate issue?

I'm having a bit of trouble knowing how to review since there seems to potentially be a decent number of such instances.

Here are my results for `git grep organization-membership`

```
app/components/organization-members.js:  classNames: ['organization-members']
app/models/organization.js:  organizationMemberships: hasMany('organization-membership', { async: true }),
app/models/user.js:  organizationMemberships: hasMany('organization-membership', { async: true }),
app/styles/app.scss:@import "components/organization-members";
app/styles/components/organization-members.scss:.organization-members {
app/templates/components/organization-profile.hbs:      {{organization-members count=membersCount members=members}}
app/templates/project/index.hbs:        {{organization-members count=membersCount members=members}}
mirage/config.js:  // GET /organization-memberships
mirage/config.js:  this.get('/organization-memberships', { coalesce: true });
mirage/config.js:  // POST /organization-memberships
mirage/config.js:  this.post('/organization-memberships');
mirage/config.js:  // GET /organization-memberships/:id
mirage/config.js:  this.get('/organization-memberships/:id');
mirage/config.js:  // PATCH /organization-memberships/:id
mirage/config.js:  this.patch('/organization-memberships/:id');
mirage/config.js:  // DELETE /organization-memberships/:id
mirage/config.js:  this.delete('/organization-memberships/:id');
mirage/scenarios/default.js:  server.create('organization-membership', { member: owner, organization, role: 'owner' });
mirage/scenarios/default.js:  server.create('organization-membership', { member: admin, organization, role: 'admin' });
mirage/scenarios/default.js:  server.create('organization-membership', { member: contributor, organization, role: 'contributor' });
mirage/scenarios/default.js:  server.create('organization-membership', { member: pending, organization, role: 'pending' });
tests/acceptance/profile-test.js:  server.createList('organization-membership', 3, { member: user, organization });
tests/acceptance/profile-test.js:  server.create('organization-membership', { member: user, organization });
tests/integration/components/organization-members-test.js:import organizationMembers from 'code-corps-ember/tests/pages/components/organization-members';
tests/integration/components/organization-members-test.js:moduleForComponent('organization-members', 'Integration | Component | organization members', {
tests/integration/components/organization-members-test.js:  page.render(hbs`{{organization-members members=members}}`);
tests/integration/components/organization-members-test.js:  page.render(hbs`{{organization-members members=members}}`);
tests/pages/components/organization-members.js:  scope: '.organization-members',
tests/pages/components/organization-profile.js:import organizationMembers from 'code-corps-ember/tests/pages/components/organization-members';
tests/pages/organization.js:    scope: '.organization-members'
tests/pages/organization.js:    scope: '.organization-members li'
tests/unit/models/organization-membership-test.js:moduleForModel('organization-membership', 'Unit | Model | organization membership', {
tests/unit/models/organization-membership-test.js:testForAttributes('organization-membership', ['role']);
tests/unit/models/organization-membership-test.js:testForBelongsTo('organization-membership', 'member');
tests/unit/models/organization-membership-test.js:testForBelongsTo('organization-membership', 'organization');
tests/unit/models/organization-test.js:    'model:organization-membership',
tests/unit/models/project-test.js:    'model:organization-membership',
tests/unit/models/user-test.js:    'model:organization-membership',
```

And `git grep organizationMember`

```
app/components/organization-profile.js:  members: mapBy('organization.organizationMemberships', 'member'),
app/components/project-card.js:  projectOrganizationMembers: mapBy('project.organization.organizationMemberships', 'member'),
app/components/user-details.js:  userOrganizations: mapBy('user.organizationMemberships', 'organization')
app/controllers/project/index.js:  members: mapBy('project.organization.organizationMemberships', 'member'),
app/models/organization.js:  organizationMemberships: hasMany('organization-membership', { async: true }),
app/models/organization.js:  organizationMembers: mapBy('organizationMemberships', 'member'),
app/models/organization.js:  pendingMemberships: filterBy('organizationMemberships', 'isPending')
app/models/user.js:  organizationMemberships: hasMany('organization-membership', { async: true }),
mirage/models/organization.js:  organizationMemberships: hasMany(),
mirage/models/user.js:  organizationMemberships: hasMany({ inverse: 'member' }),
tests/acceptance/organization-settings-profile-test.js:  server.create('organizationMembership', {
tests/acceptance/organization-settings-profile-test.js:  server.create('organizationMembership', {
tests/acceptance/organization-test.js:  server.createList('organizationMembership', 3, { organization });
tests/acceptance/projects-test.js:  server.createList('organizationMembership', 10, {
tests/integration/components/organization-members-test.js:import organizationMembers from 'code-corps-ember/tests/pages/components/organization-members';
tests/integration/components/organization-members-test.js:let page = PageObject.create(organizationMembers);
tests/integration/components/organization-profile-test.js:  organizationMemberships: memberships,
tests/integration/components/organization-profile-test.js:  assert.ok(page.organizationMembers.isVisible, 'The members component renders');
tests/integration/components/organization-profile-test.js:  assert.equal(page.organizationMembers.members().count, 3, 'The members render');
tests/integration/components/project-card-test.js:  organizationMemberships: [
tests/pages/components/organization-profile.js:import organizationMembers from 'code-corps-ember/tests/pages/components/organization-members';
tests/pages/components/organization-profile.js:  organizationMembers,
tests/unit/models/organization-test.js:testForHasMany('organization', 'organizationMemberships');
tests/unit/models/user-test.js:testForHasMany('user', 'organizationMemberships');
```

And `git grep member`

```
app/components/member-list-item.js:  classNames: ['member-list-item'],
app/components/member-list-item.js:    approve(membership) {
app/components/member-list-item.js:      membership.set('role', 'contributor');
app/components/member-list-item.js:      return membership.save().then(() => {
app/components/member-list-item.js:    deny(membership) {
app/components/member-list-item.js:      if (confirm('Are you sure want to deny their membership?')) {
app/components/member-list-item.js:        return membership.destroyRecord().then(() => {
app/components/organization-members.js:  classNames: ['organization-members']
app/components/organization-profile.js:  members: mapBy('organization.organizationMemberships', 'member'),
app/components/organization-profile.js:  membersCount: alias('members.length')
app/components/project-card-members.js:  `project-card-members` displays the first 8 members of a project and some statistics,
app/components/project-card-members.js:  including total number of members and how many members are not shown on the card, if any.
app/components/project-card-members.js:  {{project-card-members members=projectOrganizationMembers}}
app/components/project-card-members.js:  @class project-card-members
app/components/project-card-members.js:  classNames: ['project-card-members'],
app/components/project-card-members.js:    The number of members visible on the project card.
app/components/project-card-members.js:  visibleMembers: computed('members', function() {
app/components/project-card-members.js:    return this.get('members').slice(0, VISIBLE_MEMBERS_COUNT);
app/components/project-card-members.js:    Total number of members of a project.
app/components/project-card-members.js:    @property membersCount
app/components/project-card-members.js:  membersCount: alias('members.length'),
app/components/project-card-members.js:    Total number of members not shown on the project card.
app/components/project-card-members.js:  hiddenMembersCount: computed('membersCount', function() {
app/components/project-card-members.js:    return this.get('membersCount') -  VISIBLE_MEMBERS_COUNT;
app/components/project-card-members.js:    Determines if there are any hidden members who are not shown on the card.
app/components/project-card.js:  skills, and contributing members.
app/components/project-card.js:  projectOrganizationMembers: mapBy('project.organization.organizationMemberships', 'member'),
app/components/task-card.js:    let { taskUserId, members } = getProperties(this, 'taskUserId', 'members');
app/components/task-card.js:    if (members) {
app/components/task-card.js:      set(this, 'selectedOption', members.findBy('id', taskUserId));
app/components/task-card.js:  userOptions: computed('currentUserId', 'taskUserId', 'members', function() {
app/components/task-card.js:    let { currentUserId, taskUserId, members }
app/components/task-card.js:      = getProperties(this, 'currentUserId', 'taskUserId', 'members');
app/components/task-card.js:    if (members) {
app/components/task-card.js:      return createTaskUserOptions(members, currentUserId, taskUserId);
app/controllers/project/index.js:  members: mapBy('project.organization.organizationMemberships', 'member'),
app/controllers/project/index.js:  membersCount: alias('members.length'),
app/models/organization-membership.js:  member: belongsTo('user', { async: true }),
app/models/organization.js:  organizationMemberships: hasMany('organization-membership', { async: true }),
app/models/organization.js:  organizationMembers: mapBy('organizationMemberships', 'member'),
app/models/user.js:  organizationMemberships: hasMany('organization-membership', { async: true }),
app/routes/project/tasks/index.js:    let memberPromises = await get(project, 'projectUsers').then((projectUsers) => {
app/routes/project/tasks/index.js:    return RSVP.hash({ project, members: RSVP.all(memberPromises) });
app/routes/project/tasks/new.js:  ability: EmberCan.computed.ability('organization', 'membership'),
app/styles/app.scss:@import "components/member-list-item";
app/styles/app.scss:@import "components/organization-members";
app/styles/app.scss:@import "components/project-card-members";
app/styles/components/member-list-item.scss:.member-list-item {
app/styles/components/member-list-item.scss:.project-member {
app/styles/components/member-list-item.scss:.member-list-item {
app/styles/components/organization-members.scss:@mixin member-list-item($number, $margin-right) {
app/styles/components/organization-members.scss:.organization-members {
app/styles/components/organization-members.scss:    @include member-list-item(6, 3px);
app/styles/components/organization-members.scss:      @include member-list-item(9, 3px);
app/styles/components/organization-members.scss:      @include member-list-item(6, 3px);
app/styles/components/project-card-members.scss:.project-card-members {
app/templates/components/member-list-item.hbs:<div class="project-member__avatar">
app/templates/components/member-list-item.hbs:<div class="project-member__name">
app/templates/components/member-list-item.hbs:<div class="project-member__skills">
app/templates/components/member-list-item.hbs:<div class="project-member__actions">
app/templates/components/member-list-item.hbs:  {{#if (eq membership.role 'pending')}}
app/templates/components/member-list-item.hbs:    <button class="default small" {{action "approve" membership}}>Approve</button>
app/templates/components/member-list-item.hbs:    <button class="danger small" {{action "deny" membership}}>Deny</button>
app/templates/components/organization-members.hbs:{{#each (slice 0 15 members) as |user|}}
app/templates/components/organization-profile.hbs:      {{organization-members count=membersCount members=members}}
app/templates/components/organization-settings.hbs:  {{organization-menu organization=organization membership=membership}}
app/templates/components/project-card-members.hbs:  <li class="member">
app/templates/components/project-card.hbs:  {{project-card-members members=projectOrganizationMembers}}
app/templates/components/task-list-cards.hbs:    members=members
app/templates/privacy.hbs:      <li>information about your organization, organization members, projects, project volunteers, donors, location, and preferences, including your project interests, skills, abilities, and other information;</li>
app/templates/project/index.hbs:        {{organization-members count=membersCount members=members}}
app/templates/project/settings/contributors.hbs:  {{#each (filter-by 'role' 'pending' model.projectUsers) as |membership|}}
app/templates/project/settings/contributors.hbs:    {{member-list-item membership=membership user=membership.user}}
app/templates/project/settings/contributors.hbs:  {{#each (filter-by 'role' 'owner' model.projectUsers) as |membership|}}
app/templates/project/settings/contributors.hbs:    {{member-list-item membership=membership user=membership.user}}
app/templates/project/settings/contributors.hbs:  {{#each (filter-by 'role' 'admin' model.projectUsers) as |membership|}}
app/templates/project/settings/contributors.hbs:    {{member-list-item membership=membership user=membership.user}}
app/templates/project/settings/contributors.hbs:  {{#each (filter-by 'role' 'contributor' model.projectUsers) as |membership|}}
app/templates/project/settings/contributors.hbs:    {{member-list-item membership=membership user=membership.user}}
app/templates/project/tasks/index.hbs:            members=members
app/utils/create-task-user-options.js: * Takes in a list of organization members, the current user id and,
app/utils/create-task-user-options.js: * - other organization members
mirage/config.js:  * Organization memberships
mirage/config.js:  // GET /organization-memberships
mirage/config.js:  this.get('/organization-memberships', { coalesce: true });
mirage/config.js:  // POST /organization-memberships
mirage/config.js:  this.post('/organization-memberships');
mirage/config.js:  // GET /organization-memberships/:id
mirage/config.js:  this.get('/organization-memberships/:id');
mirage/config.js:  // PATCH /organization-memberships/:id
mirage/config.js:  this.patch('/organization-memberships/:id');
mirage/config.js:  // DELETE /organization-memberships/:id
mirage/config.js:  this.delete('/organization-memberships/:id');
mirage/models/organization-membership.js:  member: belongsTo('user'),
mirage/models/user.js:  organizationMemberships: hasMany({ inverse: 'member' }),
mirage/scenarios/default.js:  server.create('organization-membership', { member: owner, organization, role: 'owner' });
mirage/scenarios/default.js:  server.create('organization-membership', { member: admin, organization, role: 'admin' });
mirage/scenarios/default.js:  server.create('organization-membership', { member: contributor, organization, role: 'contributor' });
mirage/scenarios/default.js:  server.create('organization-membership', { member: pending, organization, role: 'pending' });
tests/acceptance/contributors-test.js:test('Lists owner when owner is the only member.', function(assert) {
tests/acceptance/contributors-test.js:    assert.equal(page.pendingContributors.members().count, 0, 'Pending contributors has no members listed');
tests/acceptance/contributors-test.js:    assert.equal(page.owners.members().count, 1, 'Owners has 1 member listed');
tests/acceptance/contributors-test.js:    assert.equal(page.admins.members().count, 0, 'Admins has no members listed');
tests/acceptance/contributors-test.js:    assert.equal(page.others.members().count, 0, 'Others has no members listed');
tests/acceptance/contributors-test.js:    assert.equal(page.pendingContributors.members().count, 2, 'Pending contributors has 2 members listed');
tests/acceptance/contributors-test.js:    assert.equal(page.owners.members().count, 1, 'Owners has 1 member listed');
tests/acceptance/contributors-test.js:    assert.equal(page.admins.members().count, 1, 'Admins has 1 member listed');
tests/acceptance/contributors-test.js:    assert.equal(page.others.members().count, 1, 'Others has 1 member listed');
tests/acceptance/contributors-test.js:    page.pendingContributors.members(0).approveMembership();
tests/acceptance/contributors-test.js:    assert.equal(page.pendingContributors.members().count, 1, 'Pending contributors has 1 member listed');
tests/acceptance/contributors-test.js:    assert.equal(page.others.members().count, 2, 'Others has 2 members listed');
tests/acceptance/contributors-test.js:    page.pendingContributors.members(0).denyMembership();
tests/acceptance/contributors-test.js:    assert.equal(page.pendingContributors.members().count, 0, 'Pending contributors no members listed');
tests/acceptance/contributors-test.js:    assert.equal(page.others.members().count, 2, 'Others has 2 members listed');
tests/acceptance/organization-settings-profile-test.js:    member: user,
tests/acceptance/organization-settings-profile-test.js:    member: user,
tests/acceptance/organization-test.js:    assert.ok(organizationPage.orgMembersSection.isVisible, 'The organization members component renders');
tests/acceptance/organization-test.js:    assert.equal(organizationPage.orgMembers().count, 3, 'The members render');
tests/acceptance/organization-test.js:  // no need to create membership. even non-members should be able to visit
tests/acceptance/profile-test.js:  server.createList('organization-membership', 3, { member: user, organization });
tests/acceptance/profile-test.js:  server.create('organization-membership', { member: user, organization });
tests/acceptance/projects-test.js:test('members are displayed correctly', function(assert) {
tests/acceptance/projects-test.js:    assert.equal(projectsPage.projectCard.members().count, 8, '8 members are rendered');
tests/acceptance/projects-test.js:    assert.equal(projectsPage.projectCard.memberCount.text, '+2 more', 'The "+2 more" text is rendered');
tests/acceptance/task-list-test.js:test('member can assign/reassign/unassign tasks to user', function(assert) {
tests/integration/components/member-list-item-test.js:import component from 'code-corps-ember/tests/pages/components/member-list-item';
tests/integration/components/member-list-item-test.js:moduleForComponent('member-list-item', 'Integration | Component | member list item', {
tests/integration/components/member-list-item-test.js:  page.render(hbs`{{member-list-item user=user}}`);
tests/integration/components/member-list-item-test.js:  page.render(hbs`{{member-list-item user=user}}`);
tests/integration/components/member-list-item-test.js:  set(this, 'membership', mockMembership('pending')); // pending
tests/integration/components/member-list-item-test.js:  page.render(hbs`{{member-list-item membership=membership user=user}}`);
tests/integration/components/member-list-item-test.js:  set(this, 'membership', mockMembership('contributor'));
tests/integration/components/member-list-item-test.js:  page.render(hbs`{{member-list-item membership=membership user=user}}`);
tests/integration/components/member-list-item-test.js:  let membership = Object.create({
tests/integration/components/member-list-item-test.js:  set(this, 'membership', membership);
tests/integration/components/member-list-item-test.js:  page.render(hbs`{{member-list-item membership=membership user=user}}`);
tests/integration/components/member-list-item-test.js:  let membership = Object.create({
tests/integration/components/member-list-item-test.js:  set(this, 'membership', membership);
tests/integration/components/member-list-item-test.js:  page.render(hbs`{{member-list-item membership=membership user=user}}`);
tests/integration/components/organization-members-test.js:import organizationMembers from 'code-corps-ember/tests/pages/components/organization-members';
tests/integration/components/organization-members-test.js:moduleForComponent('organization-members', 'Integration | Component | organization members', {
tests/integration/components/organization-members-test.js:test('it renders an item for each member in the list', function(assert) {
tests/integration/components/organization-members-test.js:  this.set('members', mockMembers);
tests/integration/components/organization-members-test.js:  page.render(hbs`{{organization-members members=members}}`);
tests/integration/components/organization-members-test.js:  assert.equal(page.memberCount, 3, 'The correct number of members are rendered');
tests/integration/components/organization-members-test.js:  assert.ok(page.members(0).imageSource.indexOf('image_1.png') > -1, 'The correct photo renders');
tests/integration/components/organization-members-test.js:  this.set('members', mockMembers);
tests/integration/components/organization-members-test.js:  page.render(hbs`{{organization-members members=members}}`);
tests/integration/components/organization-members-test.js:  assert.notOk(page.members(0).imageIsVisible, 'The photo does not render');
tests/integration/components/organization-members-test.js:  assert.ok(page.members(0).placeholderIsVisible, 'The placeholder renders');
tests/integration/components/organization-profile-test.js:let members = [
tests/integration/components/organization-profile-test.js:let memberships = members.map((member) => {
tests/integration/components/organization-profile-test.js:  return { id: member.id, member };
tests/integration/components/organization-profile-test.js:  organizationMemberships: memberships,
tests/integration/components/organization-profile-test.js:  assert.ok(page.organizationMembers.isVisible, 'The members component renders');
tests/integration/components/organization-profile-test.js:  assert.equal(page.organizationMembers.members().count, 3, 'The members render');
tests/integration/components/project-card-members-test.js:moduleForComponent('project-card-members', 'Integration | Component | project card members', {
tests/integration/components/project-card-members-test.js:  let members = [];
tests/integration/components/project-card-members-test.js:    members.push(Object.create({
tests/integration/components/project-card-members-test.js:  return members;
tests/integration/components/project-card-members-test.js:test('it shows all members if less than 8', function(assert) {
tests/integration/components/project-card-members-test.js:  this.set('members', allMembersVisible);
tests/integration/components/project-card-members-test.js:  this.render(hbs`{{project-card-members members=members}}`);
tests/integration/components/project-card-members-test.js:test('it shows all members if more than 8', function(assert) {
tests/integration/components/project-card-members-test.js:  this.set('members', someMembersHidden);
tests/integration/components/project-card-members-test.js:  this.render(hbs`{{project-card-members members=members}}`);
tests/integration/components/project-card-test.js:      member: user
tests/integration/components/project-card-test.js:  assert.equal(this.$('ul.project-card-members li').length, 1);
tests/integration/components/project-card-test.js:  assert.equal(this.$('ul.project-card-members li:first img').attr('src'), user.photoThumbUrl);
tests/integration/components/project-card-test.js:  assert.equal(this.$('ul.project-card-members li:first img').length, 0);
tests/integration/components/project-menu-test.js:test('when authenticated, and user can manage project, and project has pending members', function(assert) {
tests/integration/components/project-menu-test.js:  assert.equal(page.links(2).badge.text, '1 pending', 'The correct number of pending members render');
tests/integration/components/project-menu-test.js:test('when authenticated, and user can manage project, and project has no pending members', function(assert) {
tests/integration/components/project-menu-test.js:  assert.notOk(page.links(2).badge.isVisible, 'The pending members badge does not render');
tests/integration/components/task-card-test.js:      members=members
tests/integration/components/task-card-test.js:  let members = [user];
tests/integration/components/task-card-test.js:  setProperties(this, { task, members });
tests/integration/components/task-card-test.js:  let members = [user];
tests/integration/components/task-card-test.js:  setProperties(this, { task, members, taskUser });
tests/integration/components/task-card-test.js:  let members = [user1, user2];
tests/integration/components/task-card-test.js:  setProperties(this, { task, members });
tests/integration/components/task-card-test.js:  let members = [user1, user2].map((user) => proxify(user));
tests/integration/components/task-card-test.js:  setProperties(this, { task, members });
tests/integration/components/task-card-test.js:  RSVP.all(members).then(() => {
tests/integration/components/team-member-test.js:moduleForComponent('team-member', 'Integration | Component | team member', {
tests/integration/components/team-member-test.js:  this.render(hbs`{{team-member name="Nikola Begedin" imageSlug="nikola-begedin"}}`);
tests/pages/components/member-list-item.js:  scope: '.member-list-item',
tests/pages/components/member-list-item.js:    scope: '.project-member__name',
tests/pages/components/member-list-item.js:    scope: '.project-member__skills',
tests/pages/components/organization-members.js:  scope: '.organization-members',
tests/pages/components/organization-members.js:  memberCount: count('li'),
tests/pages/components/organization-members.js:  members: collection({
tests/pages/components/organization-profile.js:import organizationMembers from 'code-corps-ember/tests/pages/components/organization-members';
tests/pages/components/project-card.js:  memberCount: {
tests/pages/components/project-card.js:    scope: '.project-card-members .count'
tests/pages/components/project-card.js:  members: collection({
tests/pages/components/project-card.js:    scope: '.project-card-members',
tests/pages/components/project-card.js:    itemScope: 'li.member'
tests/pages/contributors.js:    members: collection({
tests/pages/contributors.js:      itemScope: '.member-list-item',
tests/pages/organization.js:    scope: '.organization-members'
tests/pages/organization.js:    scope: '.organization-members li'
tests/unit/abilities/task-test.js:  assert.notOk(get(ability, 'canEdit'), 'Pending project members cannot edit.');
tests/unit/abilities/task-test.js:  assert.notOk(get(ability, 'canEdit'), 'Contributor project members cannot edit.');
tests/unit/abilities/task-test.js:  assert.ok(get(ability, 'canEdit'), 'Admin project members can edit.');
tests/unit/abilities/task-test.js:  assert.notOk(get(ability, 'canAssign'), 'Pending project members cannot assign.');
tests/unit/abilities/task-test.js:  assert.ok(get(ability, 'canAssign'), 'Contributor project members can assign.');
tests/unit/abilities/task-test.js:  assert.ok(get(ability, 'canAssign'), 'Admin project members can assign.');
tests/unit/abilities/task-test.js:  assert.notOk(get(ability, 'canReposition'), 'Pending project members cannot reposition.');
tests/unit/abilities/task-test.js:  assert.ok(get(ability, 'canReposition'), 'Contributor project members can reposition.');
tests/unit/abilities/task-test.js:  assert.ok(get(ability, 'canReposition'), 'Admin project members can reposition.');
tests/unit/models/organization-membership-test.js:moduleForModel('organization-membership', 'Unit | Model | organization membership', {
tests/unit/models/organization-membership-test.js:testForAttributes('organization-membership', ['role']);
tests/unit/models/organization-membership-test.js:testForBelongsTo('organization-membership', 'member');
tests/unit/models/organization-membership-test.js:testForBelongsTo('organization-membership', 'organization');
tests/unit/models/organization-test.js:    'model:organization-membership',
tests/unit/models/project-test.js:    'model:organization-membership',
tests/unit/models/user-test.js:    'model:organization-membership',
```

This excludes some irrelevant stuff but does not attempt to deduplicate.

**Comment by begedin** [comment]
A good part of that is simply removal of all references to organization memberships, which I did not do. 

I also definitely missed a few, mostly doe to not having tests. I'm not sure what the best approach to handle it is. I would say we try to switch the remainder here, then deal with cleanup in another PR.

**Comment by begedin** [comment]
This is good for another review, and hopefully, for a merge. I think I did as much as I could with it. It's gonna be a pain to review, but changing one think kept breaking another until I cleaned it all up. I managed to reorder and organize the commits, at least, so I guess reviewing individual commits might make it easier.

**Comment by begedin** [comment]
The drop in coverage is unavoidable. None of the remaining files have a coverage drop, but we did remove a couple of well-tested files in this PR, which drops the overall average.

**Pull request merged**
