### PR TITLE
Fix broken pagination

### PR DESCRIPTION
**Pull request by ognjen-petrovic**
Per issue https://github.com/code-corps/code-corps-ember/issues/506

### CODE REVIEW

**Comment by JoshSmith** [comment]
@ognjen-petrovic thanks for the PR!

A couple quick things:

- Tests are failing because of jshint; you're just missing a semicolon.
- Can you add a failing component test for the pagination and then make that test pass with your code? Since it's a bug, we'd prefer a regression test to catch it.

🙌

**Comment by JoshSmith** [comment]
@ognjen-petrovic do you have any questions about what we need in terms of failing => passing tests?

**Comment by ognjen-petrovic** [comment]
Hi Josh,

I'm not sure...did I miss some steps?
I did the test and it passed.

Regards, Ognjen

**Comment by JoshSmith** [comment]
@ognjen-petrovic just referencing my comment from above:

> Can you add a failing component test for the pagination and then make that test pass with your code? Since it's a bug, we'd prefer a regression test to catch it.

Can work with you to identify how to do this if you need it. We want to make sure your new code is tested in the pagination component tests.

**Comment by ognjen-petrovic** [comment]
@JoshSmith 
Yes, please, instruct what I have to do.
What I did so far... fixed error (added semicolon), ran test and it passed, committed and pushed to the "patch-1".

**Comment by JoshSmith** [comment]
@ognjen-petrovic you need to change `tests/integration/components/pager-control-test.js` to be a failing test without your code, and make it pass with your code.

**Comment by ognjen-petrovic** [comment]
@JoshSmith Ah, OK, got it.

On which page (URL) I can see pagination in action, to actually see what is broken?

**Comment by JoshSmith** [comment]
On a project's tasks page. You'll need the API running locally and reduce the number of pages in the component after seeding the database. You could also just change the number of pages in the component test and observe the broken behavior there.

**Comment by JoshSmith** [comment]
@ognjen-petrovic just checking back in on this...

**Comment by ognjen-petrovic** [comment]
@JoshSmith  I cannot install Docker on my computer, it constantly fails to install and I'm not able to get the backend app running.

**Comment by JoshSmith** [comment]
@ognjen-petrovic you can accomplish this without needing the backend API. If you want to join our Slack sometime I can walk you through how.

**Comment by ognjen-petrovic** [comment]
@JoshSmith Sure, will join...

**Comment by JoshSmith** [comment]
@ognjen-petrovic awesome: http://slack.codecorps.org

**Pull request closed without merging**
