### PR TITLE
Update config for Docker

### PR DESCRIPTION
**Pull request by JoshSmith**
This is a sister PR for the API PR changing development environment configs for Docker.

### CODE REVIEW

**Comment by WenInCode** [comment]
@JoshSmith I am currently getting this error on `ember server`
```
Error: Redis connection to api.lvh.me:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by JoshSmith** [comment]
@WenInCode sorry about that. Hadn't pushed. New port changes should account for this now.

**Comment by WenInCode** [comment]
@JoshSmith looks like a CORS issue:
```
XMLHttpRequest cannot load http://api.lvh.me:5001/oauth/token/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by JoshSmith** [comment]
@WenInCode are you loading the Ember app with `http://lvh.me` or `http://localhost:4200`?

**Comment by WenInCode** [comment]
@JoshSmith It is working for me - thanks for the explanation

**Pull request merged**
