### PR TITLE
[CircleCI]: switch over to using Chrome on travis and FF and Chrome loc…

### PR DESCRIPTION
**Pull request by snewcomer**
…ally

Trying a new travis config with Chrome.

### CODE REVIEW

**Comment by snewcomer** [comment]
aaaaand just realized you aren't using travis :)  dope.  @JoshSmith how about using Chrome instead of phantom for tests.

**Comment by snewcomer** [comment]
Also, prob can delete the travis file as well, correct?  No future plans?

**Comment by begedin** [comment]
@snewcomer Feel free to remove travis. We used it at some point, IIRC, but no longer. It's just a remnant. Outside of that, this looks good, but I'd prefer to wait for a merge until @JoshSmith gets back.

**Comment by snewcomer** [comment]
@JoshSmith lmk what you think of this PR.

**Comment by JoshSmith** [comment]
@snewcomer can you rebase and then merge yourself when you're ready? Looks awesome!

**Pull request merged**
