### PR TITLE
Add attributes "min" and "step" to the donation value input field

### PR DESCRIPTION
**Pull request by Dubhghlas**
# Partial Step to Prevent Negative Donation Goal Value

Small change to the donation value input field that adds the attributes:
- min="0"
- step="1"

# Still Needed

Validation of proper value prior to saving.

## References
Progress on: #1029

### CODE REVIEW

**Comment by JoshSmith** [comment]
@Dubhghlas thanks for this! Instead of merging develop into your brach, would you mind rebasing onto develop when it's out of sync? Thanks!

**Comment by JoshSmith** [comment]
@Dubhghlas lmk when this is good to review.

**Comment by Dubhghlas** [comment]
Rebased and pushed.

**Comment by Dubhghlas** [comment]
@JoshSmith Branch has been rebased with dev.

**Comment by JoshSmith** [comment]
🙌

**Pull request merged**
