### PR TITLE
Add eslint and remove jshint

### LINKED ISSUE #491: Add ember-cli-eslint
# Problem

We want to add modern linting and eventually code style checking via https://github.com/ember-cli/ember-cli-eslint.

## Subtasks
- [ ] Add `ember-cli-eslint`

### PR DESCRIPTION
**Pull request by sarupbanskota**
# What's in this PR?

- Added `ember-cli-eslint`
- Removed jshint oriented files

Make sure any changes to code include changes to documentation.

## References
Fixes #491

### CODE REVIEW

**Comment by JoshSmith** [comment]
@sarupbanskota your build is failing because of `eslint` errors. You should be able to see the output there to know what to add to `eslint` and what to fix. Some things from the `.jshintrc` we want added over, like `server`, for example.

**Comment by sarupbanskota** [comment]
Yep - that was expected. It's pretty late here, I'll resume tomorrow. 

Will you want me to squash all commits into one, or retain sequential changes per commit?

**Comment by JoshSmith** [comment]
@sarupbanskota retain your commit history until we're done so we can see changes. Then we'll rebase and squash. More info on that is in our docs.

**Comment by JoshSmith** [comment]
@sarupbanskota you'll have to do some rebasing here when you come back to this.

**Comment by JoshSmith** [comment]
We may want to add https://github.com/DockYard/eslint-plugin-ember-suave

**Comment by JoshSmith** [comment]
@sarupbanskota just wanted to check in on this again. Thanks!

**Comment by sarupbanskota** [comment]
Hi Josh!

Been a crazy week at work - let me sort this out over the weekend :-)

Thanks!

Sarup

**Comment by JoshSmith** [comment]
@sarupbanskota no worries! Same here, actually. I'll be around all weekend if you need me.

**Comment by sarupbanskota** [comment]
Just for my notes, here's the migration status: 

- [ ] "browser": true,		
- [ ] "boss": true,		
- [ ] "curly": true,		
- [ ] "debug": false,		
- [ ] "devel": true,		
- [ ] "eqeqeq": true,		
- [ ] "evil": true,		
- [ ] "forin": false,		
- [ ] "immed": false,		
- [ ] "laxbreak": false,		
- [ ] "newcap": true,		
- [ ] "noarg": true,		
- [ ] "noempty": false,		
- [ ] "nonew": false,		
- [ ] "nomen": false,		
- [ ] "onevar": false,		
- [ ] "plusplus": false,		
- [ ] "regexp": false,		
- [ ] "undef": true,		
- [ ] "sub": true,		
- [ ] "strict": false,		
- [ ] "white": false,		
- [ ] "eqnull": true,		
- [ ] "esversion": 6,		
- [ ] "unused": true

**Comment by sarupbanskota** [comment]
Wohoo finally! Circle is green!

@JoshSmith Please review it now. There are some rules that were turned on with jshint, which I turned off on eslint. If this looks ok, I'd prefer do the following in separate PRs: 
1. Switch them on one by one, and fix relevant erroneous code
2. Get `ember-suave` / `https://github.com/netguru/eslint-config-netguru-ember` working if there's interest.

Thanks!

**Comment by JoshSmith** [comment]
This looks great and all sounds good. Would like to use the `ember-suave` plugin.

**Comment by JoshSmith** [comment]
Can you open issues for those?

**Comment by JoshSmith** [comment]
@sarupbanskota just rebase and squash your commits and we'll be good to merge!

**Pull request merged**
