### PR TITLE
Eslint/key spacing

### PR DESCRIPTION
**Pull request by sarupbanskota**
# What's in this PR?

Setup rules for `key-spacing` and fixed it for existing codebase.

Make sure any changes to code include changes to documentation.

## References
Progress on: #599

### CODE REVIEW

**Comment by JoshSmith** [comment]
@sarupbanskota this is the default in suave?

**Comment by JoshSmith** [comment]
@sarupbanskota bump.

**Comment by JoshSmith** [comment]
Hi @sarupbanskota just wanted to check in since it sadly seems like we're out of date now by a lot (lots of conflicts 😢 ).

Do you want me to close this?

**Comment by sarupbanskota** [comment]
Yes @JoshSmith, let's close this one for now.

**Pull request closed without merging**
