### PR TITLE
WIP: Use page objects for user-menu-test

### LINKED ISSUE #773: Rewrite integration tests for user-menu component to use page objects
Falls under umbrella issue #697.

## Resources

- What's a page object? [[1](http://martinfowler.com/bliki/PageObject.html),[2](https://wyeworks.com/blog/2015/5/13/using-the-page-object-pattern-with-ember-cli/)]
- [Quickstart guide](http://ember-cli-page-object.js.org/docs/v1.6.x/quickstart)
- See [`tests/pages/components/donations/create-donation.js`](https://github.com/code-corps/code-corps-ember/blob/develop/tests/pages/components/donations/create-donation.js) and [`tests/integration/components/donations/create-donation-test.js`](https://github.com/code-corps/code-corps-ember/blob/develop/tests/pages/components/donations/create-donation.js) for in-house examples of, respectively, a page object and the page object being utilized in an integration test.
- To generate a page object, run `ember generate page-object component/<component-name>` in the project directory.

### PR DESCRIPTION
**Pull request by sarupbanskota**
Closes #773 
Also under #697

### CODE REVIEW

**Comment by sarupbanskota** [comment]
@JoshSmith could you pls have a look at the CI log and provide me tips?

`The command ember exam --split=3 --weighted --parallel exited 137`

**Comment by JoshSmith** [comment]
I'd just rerun it

**Comment by sarupbanskota** [comment]
@JoshSmith I did actually, about 4 times now, same error :/

**Comment by rileytaylor** [comment]
@sarupbanskota I would recommend running the tests locally wiht ember exam to see if its more verbose. I'm not sure if ember test or exam have a registered verbose option but I'd try to get some more details. I haven't found anything for error 137 in node, ember test/exam or anything.

**Pull request merged**
