### PR TITLE
issue #448: utilizing ember-i18n addon

### PR DESCRIPTION
**Pull request by LBKinson**
Work in progress.

Currently:
- installed ember-i18n addon
- declared locale detection in application route
- employed translations on `/about` template as example

Needs:
- [ ] translations on all other templates
- [ ] translations on any dynamically generated messages (i.e. errors) within routes and components
- [ ] UI design for a user to change their locale (example below)

screenshot 2016-10-26 22 39 58
screenshot 2016-10-26 22 40 08

### CODE REVIEW

**Comment by JoshSmith** [comment]
@LBKinson yay! This is so awesome to see here. Thanks so much for kicking this off.

One thing to consider is UI-related portions of the application that consume English-language responses from the server. I know that's outside the scope of Ember, but is certainly going to make things confusing to a user who thinks they've internationalized.

At the very, _very_ least, this does make it easier for copywriters to come in and tweak things without having to jump directly into HTML.

**Comment by LBKinson** [comment]
@JoshSmith not sure what you mean, do you have an example of "UI-related portions of the application that consume English-language responses from the server"?

also, excellent linter, I'll be sure to fix those circle errors :)

**Comment by JoshSmith** [comment]
@LBKinson I mean things like our JSON API errors. http://docs.codecorpsapidevelop.apiary.io/#reference/authentication/json-web-token-exchange/exchange-email-and-password-for-token like the 401 responses from this endpoint, for example.

**Comment by begedin** [comment]
@JoshSmith We might want to, at some point in the future, consider not displaying error strings the server serves. Instead, we could rely on error IDs and use client-stored strings. It makes sense for the client do decide how to notify user of errors.

**Comment by JoshSmith** [comment]
@LBKinson did we want to break this PR up into smaller pieces and have a tracking issue for those?

**Comment by begedin** [comment]
I would also support merging this (if ready) as a first step.

We can then create issues to localize everything.

Additionally, I have an idea on writing a custom locale service for testing, with a set of custom assertions. This would allow us to

1. Check that there is a localized string present on the page/in the component template.
2. Check that there is indeed a key for it in the locale file.
3. Not check for the exact content of the key, just to avoid writing it twice.

**Comment by JoshSmith** [comment]
Hey @LBKinson looks like the rebase brought in some unintentional changes?

**Comment by LBKinson** [comment]
@JoshSmith I rebased off /develop, is there a different branch I should pull in?

**Comment by JoshSmith** [comment]
@LBKinson no, that's the right one. But sometimes the rebase process for a fork isn't as straightforward as it should be. My guess is that you rebased on the upstream's origin develop, but your own develop was out of sync.

**Comment by JoshSmith** [comment]
@LBKinson is this ready for a review right now or still in progress?

**Comment by JoshSmith** [comment]
Hi @LBKinson I'd definitely like to bring this but wasn't sure if you were still planning to loop back more in the context of this PR. Just let me know so I know for sure what direction to take this!

**Comment by JoshSmith** [comment]
Thanks for working on this! Sorry we weren't ever able to get more done in this PR, and would always love to do more here to incorporate this throughout the project.

**Pull request merged**
