### PR TITLE
Add task-card component.

### LINKED ISSUE #844: Task UI: task-card component
# Problem

- The task itself
- Should be hardcoded

## References

Progress on: #841

### PR DESCRIPTION
**Pull request by marineb**
# What's in this PR?

 

## References
Fixes #844

Progress on: #841

### CODE REVIEW

**Comment by JoshSmith** [comment]
@marineb opened a PR against your repo! Hope that helps.

**Comment by marineb** [comment]
Ok. I've rebased the branch with your changes, also removed the 2 extra sample tasks in the component. I have a quick question when you set `title="Task"` in the markup, it knows to find `task-card--task` in the SCSS? Or am I missing something in between?

**Comment by marineb** [comment]
Added a draft model, I guess I'm not sure how to connect things up. In terms of managing the time, we could use a package like this one: https://github.com/johnotander/ember-cli-dates.

**Comment by JoshSmith** [comment]
🙌

**Pull request merged**
