### PR TITLE
Update models to match Phoenix API

### PR DESCRIPTION
**Pull request by rileytaylor**
Changes all 'createdAt' properties to 'insertedAt'.

This references issue #374

### CODE REVIEW

**Comment by JoshSmith** [comment]
@rileytaylor this has a bunch of random commits in it, too.

**Comment by rileytaylor** [comment]
Changed the branch to try and merge it with the existing update-ember-for-phoenix and it pulled in a lot of stuff... swapped it back to merging with develop and its fine now,

**Comment by JoshSmith** [comment]
This doesn't change everything that needs changed yet.

I would suggest using `git grep` for this, so for example `git grep createdAt` yields me:

```
STYLEGUIDE.md:  createdAt: attr('date'),
app/components/demo-posts.js:      createdAt: moment().subtract(2, 'days'),
app/components/demo-posts.js:      createdAt: moment().subtract(3, 'days'),
app/models/comment.js:  createdAt: attr('date'),
app/models/post.js:  createdAt: attr('date'),
app/models/user.js:  createdAt: attr('date'),
app/services/current-user.js:      createdAt: user.get('createdAt'),
app/templates/components/comment-item.hbs:    {{#link-to 'slugged-route' comment.user.username class="username"}}{{comment.user.username}}{{/link-to}} commented {{moment-from-now comment.createdAt}}
app/templates/components/demo-posts.hbs:        <span class="main-description">#{{post.number}} by {{post.user.username}} {{moment-from-now post.createdAt}}</span>
app/templates/components/post-details.hbs:        {{#link-to 'slugged-route' post.user.username class="username"}}{{post.user.username}}{{/link-to}} posted {{moment-from-now post.createdAt}}
app/templates/components/post-item.hbs:  <div class="post-description">#{{post.number}} by {{post.user.username}} {{moment-from-now post.createdAt}}</div>
```

You've got the models covered, but you probably want to change the rest of those: the style guide, demo posts, current user service, and all those components that rely on it.

**Comment by JoshSmith** [comment]
:shipit:

**Pull request merged**
