### PR TITLE
Add yuidoc blocks to pager-control.js, see #223

### PR DESCRIPTION
**Pull request by pixelhandler**
# What's in this PR?

- Added yuidoc blocks in app/components/pager-control.js file

Progress on: #223

### CODE REVIEW

**Comment by JoshSmith** [comment]
@rileytaylor @pixelhandler it's a good question as to what extent we're overdocumenting in other cases and if this is the right level of documentation here. Are some of these functions self-documenting enough just by naming convention? I'm not totally positive, but am certainly open to some competing ideas here to see what direction we should take.

**Comment by rileytaylor** [comment]
@joshsmith @pixelhandler agreed. Some of the simple boolean values could go without description, but some could definitely use `@default` tags. Also the beginning header describing the entire component.

**Comment by pixelhandler** [comment]
@JoshSmith

> Are some of these functions self-documenting enough just by naming convention? 

If you plan to use generated docs, only methods with doc blocks will show up. For example here are the generated docs I use for an addon project, http://ember-jsonapi-resources.com/docs/

**Comment by pixelhandler** [comment]
@rileytaylor I'll add the defaults and the component doc block as well, thanks

**Comment by JoshSmith** [comment]
@pixelhandler I wasn't clear: I meant that you didn't need much more than `@property canShowPages`, for example, given the self-documenting nature.

**Comment by pixelhandler** [comment]
@JoshSmith cool thanks for the clarity, I do like seeing `@type` w/ `@property`

**Comment by JoshSmith** [comment]
I was unclear again! I just meant that you didn't need extra English-language description about what it means.

**Comment by pixelhandler** [comment]
with generated docs the English language description can be handy even when the property name is super targeted, there is usually some clarity that can be added. Also the generated docs too read nice with human descriptions vs variable names only, here is another example page of props, http://ember-jsonapi-resources.com/docs/classes/ApplicationAdapter.html

**Comment by JoshSmith** [comment]
Okay, then I would definitely consider adding those descriptions here, then.

**Comment by pixelhandler** [comment]
@rileytaylor @JoshSmith I updated this PR after rebasing on develop, Added doc block for the component as well as human friendly descriptions for the properties.

**Comment by JoshSmith** [comment]
👍 please do rebase and squash when you can @pixelhandler!

**Comment by pixelhandler** [comment]
@JoshSmith I already rebased (I figured maybe you'd use github's squash and merge feature).

I just squashed; so CI should run again :)

**Comment by pixelhandler** [comment]
@rileytaylor do you need to 👍 for the requested changes ?

**Comment by rileytaylor** [comment]
yes, looks like I do! Looks good now.

**Comment by JoshSmith** [comment]
🙌

**Pull request merged**
