### PR TITLE
Add 2-Step Instructions to start/hello.hbs to Clarify Signup Process

### LINKED ISSUE #217: Help text near profile picture to indicate you can change it
During the onboarding process, I didn't realize I could change my photo because I never hovered over the pic.

### PR DESCRIPTION
**Pull request by appleJax**
# What's in this PR?
- Add 2-step instructions to start/hello.hbs to clarify that users can (and should) add their photo to their profile.

# References
- Close #217

### CODE REVIEW

**Comment by JoshSmith** [comment]
Hey @appleJax on these issues would you mind instead writing the issue title as a plain English sentence of what it's doing, then in the description expand just a little bit on what you did, with "Closes #217" as a separate line?

Then I think you have access to adding labels, so saying it's `in progress` or `awaiting review` would make it easy to know what to do at a glance.

Thanks!

**Comment by appleJax** [comment]
@JoshSmith How do I add labels? I'm not sure if I have permission to do that.

**Comment by JoshSmith** [comment]
@appleJax just invited you. Accept and you'll have write permissions to this repo.

Use wisely! 🏆

**Comment by rileytaylor** [comment]
My only thought on this is more on a styles perspective. Do we want those Steps to be the same style as the other text element? We could do something as simple as some bullet points, or even a slightly different font color (i.e a lighter color to make it less important, and more visible as a sub-task)

That's very nitpicky and I'd be interested in what others thnk about that. We could also leave that alone for now and just have the text there until we go through and solidify styles.

**Comment by JoshSmith** [comment]
I don't think we need the second step, honestly. The helper text is more just for the photo, to clarify that you can upload there.

In that sense I would move it below the photo.

Does someone want to wireframe an example and we can decide on that first?

**Comment by appleJax** [comment]
I agree, having two steps for such a simple thing is a little much. Maybe use the hover image as the default image, and just change the brightness on hover? Also, on the right-hand side of the page, I think having the Code Corps members' names under their pictures would add clarity.

**Comment by rileytaylor** [comment]
Some quick mockups...
Inline:
image
Below: 
image
Arrow:
image

We've used the arrow thing a few times throughout the UI, so I figured I'd add that as an option.

**Comment by appleJax** [comment]
I vote for below. Looks good @rileytaylor!

**Comment by JoshSmith** [comment]
Might suggest minor copy change to "click here to add your photo."

**Comment by rileytaylor** [comment]
Yeah that would be better. I just used the text from the commit.

**Comment by appleJax** [comment]
Ok, here's the revised version:

screen shot 2016-08-30 at 10 10 26 pm

**Comment by rileytaylor** [comment]
Great work! Looks like you already squashed as well. Merge at will.

**Comment by JoshSmith** [comment]
Hey one sec.

**Comment by JoshSmith** [comment]
Prefer "Click to add photo".

**Comment by JoshSmith** [comment]
It sounds a little less formal, IMO. Your thoughts?

**Comment by appleJax** [comment]
I personally prefer caps on 'add' and 'photo', but it's up to you.

**Comment by rileytaylor** [comment]
That's fair... yeah less formal would be good. Capital 'Add' seems a little more commanding than we'd like.

**Comment by appleJax** [comment]
I'm gonna take a screen shot real quick. One moment...

**Comment by appleJax** [comment]
Yeah, 'Click to add photo' actually does look better now that I see them side-by-side...

**Comment by rileytaylor** [comment]
:+1: Yeah lets go with that for sure

**Comment by rileytaylor** [comment]
Merge at will once Circle CI passes it

**Pull request merged**
