### PR TITLE
add test helper for stubbing service consistently

### PR DESCRIPTION
**Pull request by sbatson5**
# What's in this PR?

We have a lot of instances for stubbing services. It would be nice to do this consistently and add some error handling for when we do it incorrectly.  Plus I love test helpers 😄 .

## References
Fixes No issue for this yet. But I can open one if that helps.

### CODE REVIEW

**Comment by sbatson5** [comment]
@JoshSmith let me know what you think of this helper. I wrote it for our app at work and found it useful and easy to use.

**Comment by JoshSmith** [comment]
Looks great! Rebase when you have a moment.

**Comment by sbatson5** [comment]
👍 Cool. I think there are a couple more tests that have stub services, so I will pull those into this PR as well.

**Comment by JoshSmith** [comment]
@sbatson5 looks good! Just squash.

**Comment by sbatson5** [comment]
Done. Squashed and rebased.

**Comment by JoshSmith** [comment]
🙌

**Pull request merged**
