### PR TITLE
Reduce post-type dropdown vertical padding

### PR DESCRIPTION
**Pull request by ethantanner**
Fixes issue [233](https://github.com/code-corps/code-corps-ember/issues/233).

I reduced the vertical padding on the post-type dropdown.

### CODE REVIEW

**Comment by JoshSmith** [comment]
I'm not sure if this necessarily solves the issue on Chrome. The design then looks a little odd for me on my screen. Is there something else that could be causing this?

**Comment by ethantanner** [comment]
Can you post a screenshot of what you are seeing? For me reducing the vertical padding just uncovers the text and keeps it vertically centered. Here is how it looks on my machine with chrome:

Without changes:
image

With changes:
image

**Comment by JoshSmith** [comment]
I guess this isn't a problem somehow? Does it even need padding?

**Comment by ethantanner** [comment]
We don't need vertical padding but we definitely need some left padding. So we could take the vertical padding down to 0.

**Comment by JoshSmith** [comment]
Okay, then let's kill the vertical padding altogether if the height is doing it.

**Comment by JoshSmith** [comment]
@ethantanner can you rebase and squash? https://github.com/code-corps/code-corps-ember/blob/develop/CONTRIBUTING.md#before-we-can-merge

**Pull request closed without merging**
