### PR TITLE
672 bem refactor colors.scss

### PR DESCRIPTION
**Pull request by rlueder**
# What's in this PR?

This is a big refactor of _colors.scss, looking forward to feedback on the changes.

Main goals were to make the stylesheet easier to scan and avoiding a few semantics issues e.g.

`.task-new-form-body {`
`border-color: $idea-background;`
`}`

Hopefully it’ll also help newcomers avoid guesswork when having to assign colors to elements.

## References

Progress on: #672

### CODE REVIEW

**Comment by rlueder** [comment]
I noticed I left a few classes behind under the Buttons and Borders section, I'll update those soon.

I also don't want to alter the design too much but I'd like to have a little more controlled variation of shades of color (grays especially, we had close to 10 variations). I'll work on being consistent with the original design by using [sass color functions](http://sass-lang.com/documentation/Sass/Script/Functions.html) like darken and lighten

**Comment by rlueder** [comment]
A little more context on the approach I took with the refactoring, the comments are interesting (until one guy hijacks them): https://www.bensmithett.com/stop-using-so-many-sass-variables/

**Comment by rlueder** [comment]
Doing a bit more research on making the most of Sass functions for colors, another good resource: 
[Aesthetic Sass 2: Colors and Palettes](https://scotch.io/tutorials/aesthetic-sass-2-colors)

**Comment by JoshSmith** [comment]
I still need to look at this but may not be until beginning of next week.

@rlueder can you help to ensure your changes don't get unmanageable for you by rebasing onto upstream develop regularly and fixing merge conflicts?

**Comment by rlueder** [comment]
Closed in favor of #846 which is way more comprehensive than this PR

**Pull request closed without merging**
